
javax:
  sql:
    DataSource:
      usersDataSource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          databaseName: "distribuida"
          user: "distribuida"
          password: "distribuida"
